### ISSUE TITLE
How to install it ?

### ISSUE THREAD

**Issue by offlinedz** [skebby11/Fata-View#2]
How to install it ? i try but it dont connect to db

**Comment by skebby11** [comment]
> How to install it ? i try but it dont connect to db

Wasn't intended to be installed, but it should work anyway as long as you fix the DB connection on function.php and you have proper database tables.

**Comment by offlinedz** [comment]
you can see the problem here [https://test.l6-6l.com](url)
when i sign up it dont create a table in DB

**Comment by skebby11** [comment]
> you can see the problem here [https://test.l6-6l.com](url)
> when i sign up it dont create a table in DB

As I said, as it wasn't intended to be installed, it does not create the tables automatically but you need to create them manually. I can provide you the mysql file to generate the tables if you want.
Or why not, update the platform for an auto install.

**Comment by offlinedz** [comment]
ah oky thnks.you can give me mysql file to generate the tables
